name: Binary Encoder/Decoder Build and Run

on:
  push:
    paths:
      - '**/*.py'
      - '**/*.yml'
  workflow_dispatch:

jobs:
  run-binary-py:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run Binary Encoder
        run: |
          echo -e "Hello World!\n" | python binarypy.py
        
        
    
