name: Binary Encoder/Decoder Build and Run

on:
  push:
    paths:
      - '**/*.py'
      - '**/*.yml'
  workflow_dispatch:

jobs:
  run-binary-py:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run Values for encoding
        run: |
          cat <<EOF > Input.txt
          encode
          Hello World!
          EOF

      - name: Run Binary Encoder
        run: |
          python binarypy.py < Input.txt >> encode_output.txt
          
        
        
    
